### ISSUE TITLE
Access theme variables

### ISSUE THREAD

**Issue by kkharji** [tinted-theming/tinted-vim#17]
Hey @fnune, awesome work thanks a lot.

I use base16 across different mediums and I like it a lot. I wonder if there's a way to access the theme variables as of now.

Currently I use https://github.com/norcalli/nvim-base16.lua and with it I was able to set highlights by querying the value of; for example `base05`.

Is this possible in current fork, and if not is there a quick way to achieve that?. I basically need global variables set whenever color/base16-------.vim is loaded so that I can do something like 

`echo g:base16.base01`.

Thanks

**Comment by GordianDziwis** [comment]
try: `:echo g:base16_gui08` or `:echo g:base16_cterm08`

**Comment by kkharji** [comment]
Oh that's awesome, thanks @BonaBeavis
