### ISSUE TITLE
Add highlights for tree-sitter

### ISSUE THREAD

**Issue by GordianDziwis** [tinted-theming/tinted-vim#2]
Like [this](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Colorschemes).

**Comment by fnune** [comment]
Cool! Didn't know about treesitter. Could you submit a PR or link me to an example PR to see which highlight groups need to be added?

**Comment by GordianDziwis** [comment]
[Here](https://github.com/glepnir/zephyr-nvim/blob/bc1a7584b435b9921e245c3621ab7524be370b2d/lua/zephyr.lua#L166) you go.

**Comment by fnune** [comment]
Gave it my best go. I think it looks pretty good!
