### ISSUE TITLE
[Feature request] Add highlights for barbar.nvim

### ISSUE THREAD

**Issue by fnune** [tinted-theming/tinted-vim#22]
`base16-vim`  currently doesn't highlight the [barbar.nvim](https://github.com/romgrk/barbar.nvim) bar. It could!

**Describe the solution you'd like**
Here are the groups that need to be defined. The color variables don't exist on `base16-vim` and need to be mapped to our values:

```vim
" barbar.vim highlighting
call <sid>hi("BufferCurrent", fg_current, bg_current, "", "")
call <sid>hi("BufferCurrentIndex", fg_special, bg_current, "", "")
call <sid>hi("BufferCurrentMod", fg_modified, bg_current, "", "")
call <sid>hi("BufferCurrentSign", fg_special, bg_current, "", "")
call <sid>hi("BufferCurrentTarget", fg_target, bg_current, "bold", "")
call <sid>hi("BufferVisible", fg_visible, bg_visible, "", "")
call <sid>hi("BufferVisibleIndex", fg_visible, bg_visible, "", "")
call <sid>hi("BufferVisibleMod", fg_modified, bg_visible, "", "")
call <sid>hi("BufferVisibleSign", fg_visible, bg_visible, "", "")
call <sid>hi("BufferVisibleTarget", fg_target, bg_visible, "bold", "")
call <sid>hi("BufferInactive", fg_inactive, bg_inactive, "", "")
call <sid>hi("BufferInactiveIndex", fg_subtle, bg_inactive, "", "")
call <sid>hi("BufferInactiveMod", fg_modified, bg_inactive, "", "")
call <sid>hi("BufferInactiveSign",   fg_subtle, bg_inactive, "", "")
call <sid>hi("BufferInactiveTarget", fg_target, bg_inactive, "bold", "")
call <sid>hi("BufferTabpages", fg_special, bg_inactive, "bold", "")
call <sid>hi("BufferTabpageFill", fg_inactive, bg_inactive, "", "")
```

Here's an example from `doom-one.vim`: https://github.com/romgrk/doom-one.vim/blame/29c3a2a3d5cb3ec001ee5aaa95de3033fbfd7a58/colors/doom-one.vim#L189

**Describe alternatives you've considered**
Use `doom-one.vim`.

**Comment by GordianDziwis** [comment]
Airlines tabs begin to annoy me, maybe I will start with barbar soon and add some highlights.

**Comment by GordianDziwis** [comment]
The highlights are linked to the default ones e.g. `BufferDefaultCurrent`. And those are [derived from `TabLineSel`](https://github.com/romgrk/barbar.nvim/blob/7c28de8c22f4c00ed43a78ae16c13dd6a248fe1a/lua/barbar/highlight.lua#L229). So they should exist.

Was this already the case when @fnune created the issue?

**Comment by fnune** [comment]
Hi! I'm sorry I have been using other themes since then :( it's been a while.

**Comment by GordianDziwis** [comment]
No prob.
