### ISSUE TITLE
[Feature request] Add highlight groups for CoC semantic tokens

### ISSUE THREAD

**Issue by nbn22385** [tinted-theming/tinted-vim#24]
**Is your feature request related to a problem? Please describe.**

`base16-vim` does not currently have the highlight groups defined for the new semantic token highlighting capability of coc.nvim.

**Describe the solution you'd like**

The highlight groups prefixed by  `CocSem_` would need to be defined and mapped to an appropriate highlight group (vim provides some built in ones that could work, like `String`, `Function`, `Include`, `Boolean`, `Keyword`, `Define`, `Macro`, `Typedef`, etc.).

See this example from the edge colorscheme: https://github.com/sainnhe/edge/blob/master/colors/edge.vim#L383

**Describe alternatives you've considered**

- Using a theme compatible with semantic tokens (edge, everforest, gruvbox-material, sonokai)
- Manually define all `CocSem_` highlight groups and link them to an existing group

**Comment by fnune** [comment]
I don't use CoC anymore and currently don't have time to implement this and test this myself, but I'd welcome a PR with something workable. Would you be willing to try this yourself? https://github.com/fnune/base16-vim#building

**Comment by nbn22385** [comment]
I could set up some basic mappings and give it a try
