### ISSUE TITLE
Remove deprecated LSP highlights on next release

### ISSUE THREAD

**Issue by GordianDziwis** [tinted-theming/tinted-vim#36]
See https://github.com/fnune/base16-vim/pull/34

**Comment by fnune** [comment]
I'm not sure we need to remove them; our theme should support older Neovim versions and can support them at no cost, right?

**Comment by GordianDziwis** [comment]
As I understand, those highlights were only used in nightly. They are not in any release yet. And nightly has changed those highlights. So with the next release we would only loose support for nightly version from before the change.

**Comment by fnune** [comment]
Awesome, makes sense!
