### ISSUE TITLE
[Feature request] Add Shapeshifter Dark theme

### ISSUE THREAD

**Issue by ghost** [tinted-theming/tinted-vim#37]
I suggest adding the Shapeshifter Dark theme. Found both it and the light version on terminal.sexy, but was sad to see the original base16-vim project for some reason only had the light variant. If anyone else wants it, I think adding the dark version here would be great, as I think it looks great!

**Comment by fnune** [comment]
@BonaBeavis I have to admit I'm looking at the repo and I'm not sure where Shapeshifter Light came from. Maybe from an old commit in https://github.com/chriskempson/base16-schemes-source?

To add a new theme, one needs to add it to the sources linked above. However, I can't find Shapeshifter there right now (either version).

**Comment by GordianDziwis** [comment]
It is `templates/vim/colors` after running make.

**Comment by GordianDziwis** [comment]
We just pull the themes and do not add themes, you will have to create an issue upstream.
