### ISSUE TITLE
[Bug report] Background colors too light for nvim-cmp?

### ISSUE THREAD

**Issue by greg0ire** [tinted-theming/tinted-vim#39]
**Describe the bug**
It's hard to read things in autocomplete menus

**Expected behavior**
A dark background (like the one in https://github.com/fnune/base16-vim/pull/38 ? )

**Screenshots**
![2021-11-11_15-46](https://user-images.githubusercontent.com/657779/141317593-9e112a00-b98d-4088-9097-514225b090c0.png)

**System**
Neovim version: v0.5.1
Any other plugins you may consider relevant: https://github.com/hrsh7th/nvim-cmp

**Minimal configuration file**
```lua
local o = vim.o

g.colors_name = 'base16-solarized-dark'
o.termguicolors = true
```

**Additional context**
I have enabled `termguicolors` otherwise it was really ugly. I'm using Alacritty configured as followed:

```
# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
```

**Comment by GordianDziwis** [comment]
Will be also fixed with https://github.com/fnune/base16-vim/pull/40
