### ISSUE TITLE
[Bug report] XML file highlighting is too light

### ISSUE THREAD

**Issue by greg0ire** [tinted-theming/tinted-vim#49]
This is a follow up of https://github.com/fnune/base16-vim/issues/39

![2021-12-26_23-22](https://user-images.githubusercontent.com/657779/147421358-856c977b-ec37-4fbf-8600-130d59044a43.png)

https://github.com/doctrine/common/blob/3.2.x/psalm.xml can be use as a sample file to reproduce the issue.

Cc @BonaBeavis in case you have a fix for this one as well :)

**Comment by GordianDziwis** [comment]
Can not reproduce, what kind of highlight is this?

**Comment by greg0ire** [comment]
Oh… I didn't realize this was not native, sorry. It comes from this plugin: https://github.com/andymass/vim-matchup

If there is anything I can do to retrieve the kind of highlighting (like run some command), let me know.

**Comment by greg0ire** [comment]
@BonaBeavis I think the answer to your question is `MatchWord`: https://github.com/andymass/vim-matchup/blob/master/plugin/matchup.vim#L46

![2022-01-03_23-18](https://user-images.githubusercontent.com/657779/147986546-38db1e40-b711-4ad2-b77e-5fd893169bb4.png)


EDIT: apparently it's linked to the group `MatchParen`.
Either you feel `MatchParen` should have different colors, or we can close this and I will follow what I just found in the README:

> You can also highlight words differently than parentheses using the MatchWord highlighting group. You might do this if you find the MatchParen style distracting for large blocks.

**Comment by GordianDziwis** [comment]
You can create a pr with the `MatchWord` highlights for vim-matchup.

**Comment by greg0ire** [comment]
What does that entail? Adding something in all of the 183 files under `colors`?

**Comment by fnune** [comment]
You can edit just the template file and then run `make`. See https://github.com/fnune/base16-vim/blob/master/CONTRIBUTING.md
