### ISSUE TITLE
[Feature request] Unify colors for 'Repeat' and 'Conditional' statements

### ISSUE THREAD

**Issue by mxt3** [tinted-theming/tinted-vim#50]
**Is your feature request related to a problem? Please describe.**

A conditional statement and loop statement are currently highlighted differently in the base16 vim themes. This seems against the base16 philosophy. I quote from the spec (https://github.com/chriskempson/base16/blob/master/styling.md):
 > Base16 aims to group similar language constructs with a single color. 

The cause of this are the following lines in the template file:
```vim
call <sid>hi("Conditional",  s:gui0E, "", s:cterm0E, "", "", "")
" ...
call <sid>hi("Repeat",       s:gui0A, "", s:cterm0A, "", "", "")
```
The two groups seem to have been intentionally assigned different colors, yet they are very related. Is there a reasoning behind this? The VS Code base16 themes to no have this difference.

**Describe the solution you'd like**

Assign the same color to the Repeat and Conditional statement keywords.

**Describe alternatives you've considered**

N.A.

**Additional context**

Here is an example of a .cpp snippet highlighted with `base16-ashes` in vim:
<img src="https://user-images.githubusercontent.com/2456835/147977761-89686a17-c8b7-4434-ad4d-c1e1c86c02cb.png" width="400" >

Here is the same base16 theme in Visual Studio Code:
<img src="https://user-images.githubusercontent.com/2456835/147977814-54cd9189-c2c2-4cf6-9901-6bb7aac1038a.png" width="400" >

The `while` and `if` keywords have the same color in VS code, as I would expect from the philosophy.

**Comment by GordianDziwis** [comment]
Good catch! The syntax highlights are a bit WIP because of the treesitter and lsp semantic token stuff. So if you see other inconsistencies, please report!
