### ISSUE TITLE
[Feature request] support transparent backgrounds

### ISSUE THREAD

**Issue by gcoelho05** [tinted-theming/tinted-vim#54]
Using a base16 colorscheme from this repo does not support transparent backgrounds.  I use a transparent background on my terminal, and would very much like to use one in vim too.

I find the way [sainnhe's gruvbox material](https://github.com/sainnhe/gruvbox-material) does this very elegant:

```
let g:gruvbox_material_transparent_background = 1  " 1 = transparent; 0 = opaque
```

Probably pointless info:
I use st with the alpha patch and xcompmgr for transparency.

**Comment by fnune** [comment]
A PR is open for that I believe https://github.com/fnune/base16-vim/pull/28

But the author hasn't acted on it again. Maybe you can take it up?

**Comment by gcoelho05** [comment]
Thanks for pointing it out, I hadn't seen that.

I would love to take it up, but I'm afraid I do not have the necessary vim script knowledge, I'm sorry.  Hopefully someone else will work on this in the future.

**Comment by fnune** [comment]
Reopening just in case I find some time to do it.
