### ISSUE TITLE
Makefile is missing

### ISSUE THREAD

**Issue by GordianDziwis** [tinted-theming/tinted-vim#62]
While testing this pull request https://github.com/base16-project/base16-vim/pull/61, I saw that only the template was changed.
We should add a Makefile again, for running the base16-builder-go against the repo.

**Comment by JamyGolden** [comment]
We use [base16-builder-go](https://github.com/base16-project/base16-builder-go) to generate the colorschemes. The [CONTRIBUTING.md](https://github.com/base16-project/base16-vim/blob/main/CONTRIBUTING.md) has instructions on how to build using the builder.
