### ISSUE TITLE
[Bug report] base16-material.vim broken as of latest release

### ISSUE THREAD

**Issue by PatTheMav** [tinted-theming/tinted-vim#68]
## Describe the bug

With yesterday's update at the very least `base16-material.vim` seems to be broken - launching vim yields the following error:

```
line  411:
W18: Invalid character in group name
line  412:
W18: Invalid character in group name
line  413:
W18: Invalid character in group name
line  414:
W18: Invalid character in group name
line  415:
W18: Invalid character in group name
line  416:
W18: Invalid character in group name
line  420:
W18: Invalid character in group name
line  421:
W18: Invalid character in group name
line  431:
W18: Invalid character in group name
line  434:
W18: Invalid character in group name
line  435:
W18: Invalid character in group name
```

## Expected behavior

vim loads without any errors by themes added via `base16-vim`.

## **System**

**Vim or Neovim:**

Vim

**Vim or Neovim version:**

9.0.1000

**Any other plugins you may consider relevant:**

N/A

## Minimal configuration file

No configuration file needed, loading the plugin itself is sufficient to trigger the bug (the theme does not even need to be selected as the error occurs in `vim90/syntax/synload.vim[19]`.

## Additional context

N/A

**Comment by pfheatwole** [comment]
Breakage is from commit ca6fb38b that added an `@` to the group names, which is only supported in neovim.

@tarebyte: can we please revert to a compatible `group-name`?

**Comment by tarebyte** [comment]
That's up to the maintainer, I don't have access to the repository sorry!

**Comment by PatTheMav** [comment]
@BonaBeavis Would you be able to revert the merge/commit? Or would it be easier for @tarebyte to open a new PR accomodating vanilla vim fixing the issue?

**Comment by diegodorado** [comment]
I am facing the same issue.

Seems a bit irresponsible to not be willing to fix/revert the PR that broke it for vim users.

**Comment by diegodorado** [comment]
I rolled back to `1f052d80bfa522b8b6eb5d09fac729a528747662` and it works for me.
Tried your PR @BonaBeavis, but I saw comments picking incorrect colors

**Comment by GordianDziwis** [comment]
@diegodorado What comments were not correctly highlighted?

**Comment by tilgovi** [comment]
@BonaBeavis it does appear that maybe the colors work, but vim spews the errors above on startup and asks the user to press enter to continue. It's not a great experience.

**Comment by pfheatwole** [comment]
Thanks, @BonaBeavis and @JamyGolden! Appreciated.
