### ISSUE TITLE
[Bug report] Lualinenotices error

### ISSUE THREAD

**Issue by FormalSnake** [tinted-theming/tinted-vim#76]
## Describe the bug

I get this error in `:Lualinenotices`: `theme(base16): nvim-base16 is not currently present in your runtimepath, make sure it is properly installed, fallback to default colors.`

## Expected behavior

No error and the theme should show up

## Screenshots
Lualine doesn't get the theme, and gives me the error
<img width="1677" alt="Screenshot 2024-02-08 at 16 34 28" src="https://github.com/tinted-theming/base16-vim/assets/90651091/16e2d51e-11da-48d2-81b0-eb7cd122864b">

## **System**

**Vim or Neovim:** Neovim

**Vim or Neovim version:** 0.9.4

## Minimal configuration file

The Base16 script:
```lua
return {
  {
    "tinted-theming/base16-vim",
    priority = 1000,
    config = function()
      local cmd = vim.cmd
      local g = vim.g
      local current_theme_name = os.getenv("BASE16_THEME")
      -- if current_theme_name == 'black-metal-bathory' then
      --   cmd('colorscheme vesper')
      --[[ else ]]
      if current_theme_name and g.colors_name ~= "base16-" .. current_theme_name then
        cmd("let base16colorspace=256")
        cmd("colorscheme base16-" .. current_theme_name)
      end
    end,
  },
}
```
Relevant lualine config:
```lua
    opts.options = {
      theme = "auto",
      icons_enabled = true,
      component_separators = { left = "", right = "" },
      section_separators = { left = "", right = "" },
      disabled_filetypes = {
        statusline = {
          "help",
          "startify",
          "dashboard",
          "neo-tree",
          "packer",
          "neogitstatus",
          "NvimTree",
          "Trouble",
          "alpha",
          "lir",
          "Outline",
          "spectre_panel",
          "toggleterm",
          "qf",
        },
        winbar = {},
      },
    }
```

## Additional context

I am using Lazyvim, but I had this issue for a while.

**Comment by JamyGolden** [comment]
Hey @FormalSnake, I created a Lualine PR a long time ago. I've just pinged the maintainer about it so hopefully they merge: https://github.com/nvim-lualine/lualine.nvim/pull/1006

**Comment by FormalSnake** [comment]
Thanks, I appreciate it.

**Comment by JamyGolden** [comment]
@FormalSnake the maintainer merged it so hopefully this is resolved. Can you test it out with the updated lualine version and see if it fixes the issue?

**Comment by JamyGolden** [comment]
I'm going to close the issue since the lualine maintainer merged the PR.
