### ISSUE TITLE
[Bug report] New Neovim colors

### ISSUE THREAD

**Issue by peterfication** [tinted-theming/tinted-vim#81]
## Describe the bug

Neovim 0.10 changed its color groups and now the themes don't fully work anymore.

See https://neovim.io/doc/user/news-0.10.html

> These Nvim specific highlight groups are now defined in a meaningfully different way and might need an update:
[hl-FloatBorder](https://neovim.io/doc/user/syntax.html#hl-FloatBorder) is linked to [hl-NormalFloat](https://neovim.io/doc/user/syntax.html#hl-NormalFloat) instead of [hl-WinSeparator](https://neovim.io/doc/user/syntax.html#hl-WinSeparator).
> - [hl-NormalFloat](https://neovim.io/doc/user/syntax.html#hl-NormalFloat) is not linked to [hl-Pmenu](https://neovim.io/doc/user/syntax.html#hl-Pmenu).
> - [hl-WinBar](https://neovim.io/doc/user/syntax.html#hl-WinBar) has different background.
> - [hl-WinBarNC](https://neovim.io/doc/user/syntax.html#hl-WinBarNC) is similar to [hl-WinBar](https://neovim.io/doc/user/syntax.html#hl-WinBar) but not bold.
> - [hl-WinSeparator](https://neovim.io/doc/user/syntax.html#hl-WinSeparator) is linked to [hl-Normal](https://neovim.io/doc/user/syntax.html#hl-Normal) instead of [hl-VertSplit](https://neovim.io/doc/user/deprecated.html#hl-VertSplit).

## Expected behavior

The template needs to be adjusted accordingly.

## **System**

**Vim or Neovim:** Neovim

**Vim or Neovim version:** 0.10

**Any other plugins you may consider relevant:**

**Comment by AhmedSoliman** [comment]
Is there a short-term solution to this until a proper PR gets merged?
