### ISSUE TITLE
[Bug report] Comments are non-italic for Treesitter highlight groups

### ISSUE THREAD

**Issue by floriankessler** [tinted-theming/tinted-vim#84]
Comments are non-italic for Treesitter highlight groups
https://github.com/tinted-theming/base16-vim/blob/8a2190069b1c91c104e1de5ec57431d71472be8e/templates/default.mustache#L306

while they are for standard syntax.
https://github.com/tinted-theming/base16-vim/blob/8a2190069b1c91c104e1de5ec57431d71472be8e/templates/default.mustache#L259

I'd expect comments to be shown using italics for TS-based setups, too

**Comment by belak** [comment]
Thanks for the report! That makes sense to me. Should be fixed in 7ba1012b052e6ec232e5602795eb5b977156a1c7. I'll trigger a manual rebuild as well.

**Comment by belak** [comment]
Should be fixed in main. The built commit is dfc1d89d56404cfd8e97f5d0dd1c8a7a019e68ce. Thanks again for the report!

**Comment by floriankessler** [comment]
Works for me, now. Thanks for all your work!
