### ISSUE TITLE
Cursor is not visible for matched brackets

### ISSUE THREAD

**Issue by joshbode** [tinted-theming/tinted-vim#92]
## Describe the bug

After commit 41ca21b I have been unable to see the cursor when it is on a matched bracket.

## Expected behaviour

The cursor should not disappear when on a matched bracket.

### Working

Up to and including 41ca21b, the cursor (positioned in the first column over the `^`) is visible along with the matching bracket:
<img width="91" alt="image" src="https://github.com/user-attachments/assets/a69b8141-5468-4a57-8257-119628072542">
The same, but in the last column:
<img width="95" alt="image" src="https://github.com/user-attachments/assets/e0e3db43-0220-4834-ba9c-81c30ce53bd8">

### Not Working
All commits after 41ca21b only the matching bracket on the right is visible:
<img width="112" alt="image" src="https://github.com/user-attachments/assets/9097717f-079d-4162-b4c0-18a331206919">
The same, but in the last column:
<img width="109" alt="image" src="https://github.com/user-attachments/assets/e31c76d7-4914-46c6-a52f-c9536e1a2e83">

## **System**

Neovim v0.10.2, macOS, Alacritty, tinty, tmux
Also using `HiPhish/rainbow-delimiters.nvim` although disabling this and all other plugins doesn't fix the issue.
Theme in examples is `base16-ayu-dark` but the issue occurs in other themes (both light and dark)

**Comment by joshbode** [comment]
I've also just noticed that the usual tildes that pad the end of the screen are invisible (not that I miss them greatly!):

On and before 41ca21b:
<img width="98" alt="image" src="https://github.com/user-attachments/assets/9049d724-de9f-4f0c-92a6-f08070996c79">

After 41ca21b:
<img width="107" alt="image" src="https://github.com/user-attachments/assets/90ed6eb3-460d-48aa-8cf9-3e17c86ccc60">

**Comment by joshbode** [comment]
the issue appears to be related to the highlight:
```
call <sid>hi('MatchParen',     '', '', '', '',  'inverse', '')
```
which was formerly:
```
call <sid>hi("MatchParen",    "", s:gui03, "", s:cterm03,  "", "")
```

**Comment by GordianDziwis** [comment]
That the tildes are invisible is intentional.

The disappearing cursor is not. I will fix it.

**Comment by GordianDziwis** [comment]
Quick fix: `let g:matchparen_disable_cursor_hl=1`

**Comment by joshbode** [comment]
Thank you, @GordianDziwis :)
