### ISSUE TITLE
[Bug report] Latest commits broke highlighting

### ISSUE THREAD

**Issue by acidghost** [tinted-theming/tinted-vim#93]
## Describe the bug

After updating from commit 577fe8125d74ff456cf942c733a85d769afe58b7 to 58bb5f11a5ff5fe0893a005f69f1cbddddf272ff I noticed highlighting with most (maybe all) tree-sitter grammars changed.

As an example, look at the following case for markdown: ![Screenshot 2024-12-10 at 18 58 11](https://github.com/user-attachments/assets/b33fe2ec-9f3c-48af-a516-0d684878a071)

## Expected behavior

Highlight colors should not change and be the ones defined in the theme.

## Screenshots

See above.

## **System**

**Vim or Neovim:** Neovim

**Vim or Neovim version:** v0.10.2

**Any other plugins you may consider relevant:** nvim-treesitter (commit `337b503688eccb3046547661e4c738e674548fcf`)

## Minimal configuration file

Unfortunately I don't have time to create a small reproducer at the moment.. But relevant `vimrc` config is [here](https://github.com/acidghost/dotfiles/blob/164873cf9bba83e266ca845c5af5d1291c42c24e/vim/vimrc#L147-L161).

**Comment by acidghost** [comment]
Colors here seem to be associated differently: https://github.com/tinted-theming/tinted-vim/compare/577fe8125d74ff456cf942c733a85d769afe58b7...58bb5f11a5ff5fe0893a005f69f1cbddddf272ff#diff-8e4da39bbefb342dbac24c7b8fe153c9e2b12798d48a2ea5a75721d462ed88faL68-R70

**Comment by GordianDziwis** [comment]
The changed highlights from your Markdown example were intentional.
There is no need to highlight **bold** or _italic_ text becaues they are already rendered bold and italic. Setting a highlight for the whole Markdown code block looks bad in LSP floats with highlights.

Also, the theme only defines the colors and not where they are applied.

Do you have an example where the highlights are not just different but inconsistent or where you think they can be improved?

**Comment by acidghost** [comment]
I don't know much about how this repo works, nor how vim syntax highlighting works, so excuse me if the following questions have obvious answers.

> There is no need to highlight **bold** or _italic_ text becaues they are already rendered bold and italic.

This seems like a deliberate choice that users should be able to do by themselves... After years with the same colorscheme, it's really jarring to have a new one kind of forced upon you.

Did the colors I had before the update came from this plugin? If so, is there any change I can make to bring them back with the latest version of this plugin?

> Setting a highlight for the whole Markdown code block looks bad in LSP floats with highlights.

This seems a subjective stance. I did not notice anything ugly before and was really quite happy with my colorscheme.

Also the same color change holds for inline code (e.g. `this formatting`): from orange to white, without any kind of formatting / highlighting, really.

> Also, the theme only defines the colors and not where they are applied.

I guess this may help me fix the issues in my own configs. Can you please elaborate more? Can you give an example of how to apply colors to specific parts? Trying to look at previous commits I cannot seem to find changes where colors were applied to syntactic elements and then not anymore.
 
> Do you have an example where the highlights are not just different but inconsistent or where you think they can be improved?

It was just perfect the way it was before 😆

**Comment by GordianDziwis** [comment]
> Also the same color change holds for inline code (e.g. this formatting): from orange to white, without any kind of formatting / highlighting, really.

Sorry, this was an oversight. I fixed it here: https://github.com/tinted-theming/tinted-vim/pull/95

Yes, color schemes are highly subjective, so you have three options:

1. **It was perfect:** Pin your version of the plugin to https://github.com/tinted-theming/tinted-vim/commit/2ed5ac1f99adf590d91a9f8d872286bafffaa3f3.
2. **Override specific highlights:** [How-to](https://github.com/tinted-theming/tinted-vim#customization)
3. **Report highlights:** Open an issue here

There are some [mappings](https://github.com/tinted-theming/tinted-vim/blob/main/CONTRIBUTING.md#improving-the-highlights) you can use to identify highlights.

**Comment by acidghost** [comment]
I was missing all the new docs, that helps a lot! Thank you!

With the last couple of fixes you made, I managed to bring most of the colors back to what I had by adding the following:

```vim
    call Tinted_Hi("Identifier", g:tinted_gui05, "", g:tinted_cterm05, "", "none", "")
    call Tinted_Hi("Folded", g:tinted_gui02, "", g:tinted_cterm02, "", "none", "")
    call Tinted_Hi("MatchParen", "", g:tinted_gui03, "", g:tinted_cterm03, "none", "")
    call Tinted_Hi("@markup.raw", g:tinted_gui09, "", g:tinted_cterm09, "", "none", "")
    call Tinted_Hi("@markup.raw.block", g:tinted_gui09, "", g:tinted_cterm09, "", "none", "")
    call Tinted_Hi("@markup.link", g:tinted_gui0A, "", g:tinted_cterm0A, "", "none", "")
    call Tinted_Hi("@markup.link.label", g:tinted_gui0C, "", g:tinted_cterm0C, "", "bold", "")
    call Tinted_Hi("@markup.link.url", g:tinted_gui0E, "", g:tinted_cterm0E, "", "underline", "")
```

I checked also a couple of other programming languages (Rust, Python) and LaTeX. The programming languages seem to look much better (kudos 🙌), but LaTeX seems strange (although I haven't worked with it in a couple of months).

I'll continue to keep an eye if I see something strange, I'll open a new issue if that happens.

BTW this issue would not have happened if there was a Neovim plugin manager that uses semantic versioning or something. Then I would not have been surprised by the update..

**Comment by GordianDziwis** [comment]
Improvements and Feedback would be very much appreciated!
